before:
  hooks:
    - go mod download
builds:
  - id: grfd
    main: cmd/grfd/grfd.go
    binary: grfd
    env:
      - CGO_ENABLED=0
    ldflags: -s -w -X github.com/pehlicd/grfd/cmd.grfd.versionString={{ .Tag }} -X github.com/pehlicd/grfd/cmd.grfd.buildDate={{ .Date }} -X github.com/pehlicd/grfd/cmd.grfd.buildCommit={{ .Commit }}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - builds:
      - grfd
    name_template: "{{ .ProjectName }}_{{ .Tag }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    wrap_in_directory: false
    format: tar.gz
    files:
      - LICENSE